import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./style/globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false


const fontLato = Lato({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontLato.className} ${fontLato.className} h-full antialiased`}
      data-set-theme=""
      suppressHydrationWarning
    >
      <SpeedInsights />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
